### PR TITLE
T3branch External UI

### PR DESCRIPTION
**Pull request by Moksh-Mehta7**
The following merge request introduces following changes:

- A new cursor icon.
- Fresh backgrounds for the main menu and settings screens.
- Story screen has been updated with the inclusion of "continue" and "skip" buttons.
- The previously non-functional "Help" button on the Main Menu is now operational.
- Sound effects for button clicks within the external UI.
- A back button on the LevelSelectScreen.

### CODE REVIEW

**Review by The-AhmadAA — CHANGES_REQUESTED** [review]
Fix merge conflict and request review.

**Comment by Gaganx0** [comment]
@The-AhmadAA merge is done.

**Review by The-AhmadAA — APPROVED** [review]

**Review by The-AhmadAA — CHANGES_REQUESTED** [review]
There seems to be a bug that causes the main menu buttons to be unusable if you enter the help screen and then exit

**Comment by aadityayadav17** [comment]
@The-AhmadAA thanks for noting that. we have fixed that and also merged again with the main

**Review by The-AhmadAA — APPROVED** [review]
Thanks for resolving that, happy for merge to go ahead

**Review by samsully — APPROVED** [review]
Looks great, happy to merge, didn't find any issues.

**Pull request merged**
