### PR TITLE
Team 4   waves

### PR DESCRIPTION
**Pull request by samsully**
Changes include adding difficulty and organising the mobs into specific waves. Most changes were made in WaveFactory, Forest Game Area and NPC Factory. Please note that it has not been cleaned up and any functions which had no usages but generated mobs were hashed out because of changes. All mob generating functions have had a health input added so the health can be changed for different waves. Because of this a number of tests have been hashed out, however this will be completed by us and will be done before the end of the sprint.  

Request Changes: The fireboss has currently be changed out with the IceBoss. Splitting xenos have not been removed . The reason the frequency was different was because there were 2 types of xenos and only two mobs in the possible mob pool for each planet. As spliiting mobs has been removed this should now be more frequent. As for the bosses they occur every 5 waves. For wave 5 there is one boss, wave 10 2 bosses and 15 there are three bosses which is why you haven't seen them yet.

### CODE REVIEW

**Review by The-AhmadAA — APPROVED** [review]
Good work! Happy for this merge to go ahead

**Review by Mohamad11Dab — APPROVED** [review]
LGTM !

**Review by MiniSoda17 — CHANGES_REQUESTED** [review]
Hi, sorry just a few changes to be requested. Splitting Xeno's is not something we intended to have so please remove this, I noticed you guys added it back but it was only for testing the splitting component. In the game, it is quite weird because the xeno will split into water slimes which makes no sense. Next, the frequency of water queens and skeletons is very low, almost to the point where I never see them but the xeno's are popping up alot. Is it possible to replace the xeno's with the water queens and skeletons because that's what should be showcased for the planets. Finally, for the mob bosses, I do not see them showing up in-game, might be cause all the mobs can't really die yet, but not sure how you guys implemented this. But can you implement it so that it'll show up no matter what, just so that the boss can be seen within main. **Important note** But when doing this, don't include the demon/fire boss, it is currently causing some problems to make the game crash, just have another boss replacing it for now. Thanks!

**Comment by Hasakev** [comment]
Hi sorry for any troubles, our PR was pushed before you guys (but you were before us) [sorry about that!] You'll need to merge main again (there shouldn't be many major conflicts except for MainGameArea)

**Review by MiniSoda17 — APPROVED** [review]
Thanks for the changes, LGTM!

**Pull request merged**
