### PR TITLE
Team 3 Pull Request Sprint 4

### PR DESCRIPTION
**Pull request by Moksh-Mehta7**
The following merge request introduces following changes:

- Tutorial of the Game
- HelpScreen
- Improve StoryScreen
- Fixed resizing issue on MainMenuScreen and SettingsScreen
- Add Game Title
- LevelLock
- Level description on LevelSelectScreen
- LoadingScreen
- WinningScreen and NextLevelScreen
- LoosingScreen

### CODE REVIEW

**Review by meganroxburgh — APPROVED** [review]
Looks great! Keen to see the win screen in the game :)

**Review by BlairCannon97 — APPROVED** [review]
Some welcome additions here, good stuff!

**Comment by Hasakev** [comment]
New bug: If you pause and click level select you can directly access the new level (locked before) - can make it a feature 🤣

**Review by The-AhmadAA — APPROVED** [review]

**Review by Hasakev — APPROVED** [review]

**Comment by Hasakev** [comment]
Hi please merge main again

**Pull request merged**
