### PR TITLE
Team6  projectile

### PR DESCRIPTION
**Pull request by ElanagaiArivuchelvan**
Added the attack animations for the mob balls

### CODE REVIEW

**Review by gregchan550 — CHANGES_REQUESTED** [review]
Hey guys, there are still unresolved conflicts. Please make sure you're pulling from main appropriately.

**Review by MiniSoda17 — CHANGES_REQUESTED** [review]
Hey guys, there are still unresolved conflicts. Please make sure you're pulling from main appropriately.

**Review by cindyle1 — CHANGES_REQUESTED** [review]
Hey guys, there are still unresolved conflicts. Please make sure you're pulling from main appropriately.

**Comment by The-AhmadAA** [comment]
Please merge from main again to incorporate the latest changes and resolve merge conflicts

**Pull request closed without merging**
