### PR TITLE
Team 4 Levels - General Levels Updates

### PR DESCRIPTION
**Pull request by max9753**
The pull request include several features of levels that have been created such as:

- Levels begin with game. Spawn mobs after an interval (player gets time to setup stuff)
- Levels end when all mobs are killed
- Also basic service methods for UI team to implement a display for a player to see how long until mobs are spawned or a level starts etc. Also service methods for seeing how many mobs remain in a level.

### CODE REVIEW

**Review by Mohamad11Dab — APPROVED** [review]
LGTM !

**Review by MiniSoda17 — APPROVED** [review]
Looks Good!

**Review by AlasdairS4698737 — COMMENTED** [review]
There appears to be no function for pausing the wave timer mid-game, only startWaveTimer() and stopWaveTimer() which appear to only work at the setup and cleanup of the stage.
I'd like for WaveTask to have some method of pausing the in-between waves timer that can I can access with the pause menu entity.

**Review by shiv-0831 — APPROVED** [review]
There are some minor javadoc errors in getNextWaveTime() and getWaveCount() methods in WaveService. Other than that, everything else looks good!

**Pull request merged**
